/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;
/**
 * BenefitDetail
 */

public class BenefitDetail {

  private java.util.Date hiringDate = null;

  private String contractKey = null;


  private java.util.Date activationDate = null;

  private String type = null;

  /**
   * Indicates the status of the benefit.   * &#x60;INITIAL&#x60; -  Indicates the start of benefit.   * &#x60;EVALUATION&#x60; - Indicates when the benefit is in Evaluation.   * &#x60;FINAL&#x60; - Indicates the final phase of benefit. 
   */
/**
 * Adds 10 to the age
 * @param value - The age to add 10 to
 * @returns {value} - The age + 10
 */
  public enum StatusEnum {
    /**
	 * @param String
   * @param String
   * @param String
	 */
    INITIAL("INITIAL"),
    EVALUATION("EVALUATION"),
    FINAL("FINAL");

    private String value;
/**
	 * @param String
	 */
    StatusEnum(String value) {
      this.value = value;
    }

    /**
   * Indicates the key contract for the benefit
   * @return value
  **/
    public String getValue() {
      return value;
    }
  }

  private StatusEnum status = null;

  private java.util.Date lastEvaluationDate = null;

  private java.util.Date cutOfDate = null;

  private CardDetail card = null;

   /**
   * This date specifies the date of contracting the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return hiringDate
  **/
  
  public java.util.Date getHiringDate() {
    if (this.hiringDate != null) {
      return new java.util.Date(this.hiringDate.getTime());
    } else {
      return null;
    }
  }
/**
	 * @param Date
	 */
  public void setHiringDate(java.util.Date hiringDate) {
    if (hiringDate != null) {
        this.hiringDate = new java.util.Date(hiringDate.getTime());
    } else {
        this.hiringDate = null;
    }
  }

   /**
   * Indicates the key contract for the benefit
   * @return contractKey
  **/
  public String getContractKey() {
    return contractKey;
  }
/**
	 * @param String
	 */
  public void setContractKey(String contractKey) {
    this.contractKey = contractKey;
  }

   /**
   * This date specifies the date of activation of the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return activationDate
  **/
  public java.util.Date getActivationDate() {
    if (this.activationDate != null) {
      return new java.util.Date(this.activationDate.getTime());
    } else {
      return null;
    }
  }
/**
	 * @param Date
	 */
  public void setActivationDate(java.util.Date activationDate) {
    if (activationDate != null) {
      this.activationDate = new java.util.Date(activationDate.getTime());
    } else {
        this.activationDate = null;
    }
  }

   /**
   * Indicates the benefit type
   * @return type
  **/
  public String getType() {
    return type;
  }
/**
	 * @param String
	 */
  public void setType(String type) {
    this.type = type;
  }

   /**
   * Indicates the status of the benefit.   * &#x60;INITIAL&#x60; -  Indicates the start of benefit.   * &#x60;EVALUATION&#x60; - Indicates when the benefit is in Evaluation.   * &#x60;FINAL&#x60; - Indicates the final phase of benefit. 
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }
/**
	 * @param StatusEnum
	 */
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

   /**
   * Indicates the last evaluation date for the benefit.[ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return lastEvaluationDate
  **/
  public java.util.Date getLastEvaluationDate() {
    if (this.lastEvaluationDate != null) {
      return new java.util.Date(this.lastEvaluationDate.getTime());
    } else {
      return null;
    }
  }
/**
	 * @param Date
	 */
  public void setLastEvaluationDate(java.util.Date lastEvaluationDate) {
    if (lastEvaluationDate != null) {
      this.lastEvaluationDate = new java.util.Date(lastEvaluationDate.getTime());
    } else {
        this.lastEvaluationDate = null;
    }
  }

   /**
   * This date specifies the date of finish of the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return cutOfDate
  **/
  public java.util.Date getCutOfDate() {
    if (this.cutOfDate != null) {
      return new java.util.Date(this.cutOfDate.getTime());
    } else {
      return null;
    }
  }
/**
	 * @param Date
	 */
  public void setCutOfDate(java.util.Date cutOfDate) {
    if (cutOfDate != null) {
      this.cutOfDate = new java.util.Date(cutOfDate.getTime());
    } else {
        this.cutOfDate = null;
    }
  }

   /**
   * Get card
   * @return CardDetail
  **/
  public CardDetail getCard() {
    return card;
  }
/**
	 * @param CardDetail
	 */
  public void setCard(CardDetail card) {
    this.card = card;
  }
}
