/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

/**
 * Retrieves the payment card basic information
 */
public class PaymentDetail {
	private Integer amountPayment = null;

	private Integer minimumAmount = null;

	private java.util.Date operationDate = null;

	/**
	 * Indicates the date on which the payment was made. [ISO 8601]
	 * (https://www.iso.org/iso-8601-date-and-time-format.html
	 * 
	 * @return operationDate
	 **/
	public java.util.Date getOperationDate() {
		if (operationDate != null) {
			return new java.util.Date(this.operationDate.getTime());
		  } else {
			return null;
		  }
	}
/**
	 * @param Date
	 */
	public void setOperationDate(java.util.Date operationDate) {
		if (operationDate != null) {
			this.operationDate = new java.util.Date(operationDate.getTime());
		  } else {
			  this.operationDate = null;
		  }
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PaymentDetail {\n");

		sb.append("    amountPayment: ")
				.append(toIndentedString(amountPayment)).append("\n");
		sb.append("    minimumAmount: ")
				.append(toIndentedString(minimumAmount)).append("\n");
		sb.append("    operationDate: ")
				.append(toIndentedString(operationDate)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}
/**
   * Displays if the customer has used digital channels.
   * @return amountPayment
  **/
	public java.lang.Integer getAmountPayment() {
		return this.amountPayment;
	}
/**
	 * @param Integer
	 */
	public void setAmountPayment(java.lang.Integer amountPayment) {
		this.amountPayment = amountPayment;
	}
/**
   * Displays if the customer has used digital channels.
   * @return minimumAmount
  **/
	public java.lang.Integer getMinimumAmount() {
		return this.minimumAmount;
	}
/**
	 * @param Integer
	 */
	public void setMinimumAmount(java.lang.Integer minimumAmount) {
		this.minimumAmount = minimumAmount;
	}
/**
 * Retrieves the period basic information
 */
	/**
 * Allocates a new <code>String</code> that contains characters from
 * a subarray of the character array argument. The <code>offset</code>
 * argument is the index of the first character of the subarray and
 * the <code>count</code> argument specifies the length of the
 * subarray. The contents of the subarray are copied; subsequent
 * modification of the character array does not affect the newly
 * created string.
 *
 * @param      amountPayment    array that is the source of characters.
 * @param      minimumAmount   the initial offset.
 * @param      operationDate    the length.

 */
	public PaymentDetail() {
	}

	/**
 * Retrieves the period basic information
 */
/**
 * Adds two values.
 *
 * @param amountPayment - first numeric value for the ADD operation
 * @param minimumAmount -  second numeric value for same purposes
 * @param operationDate -  second numeric value for same purposes

 */
	public PaymentDetail(java.lang.Integer amountPayment,
			java.lang.Integer minimumAmount, java.util.Date operationDate) {
		this.amountPayment = amountPayment;
		this.minimumAmount = minimumAmount;
		this.operationDate = new java.util.Date(operationDate.getTime());
	}

}
